### PR TITLE
Use object abstractions instead of Fluent

### PR DESCRIPTION
**Pull request by CristianLlanos**
This is a step towards a needed refactor that will enable the package to generate more than models.

The main effort of this PR is to get rid of Fluent within the codebase and replace it with object abstractions that will help us understand how the code works under the hood. Tools such as PhpStorm will be able help us navigate the code that was  hidden by Fluent up till now.

- Parameter and return types have been added for most clases. Some were left untouched, but the idea is to go towards a more predictable code and we need types for that.
- I'm also including some code style configurations
- And the inclusion of Behat as our new testing framework. Works well with PHPUnit it think. So the rest of our tests will keep working until those get migrated.

### CODE REVIEW

**Review by AdamLenda — APPROVED** [review]
@CristianLlanos I've scanned through this and it appears solid. 

Please merge this when you have a moment.

**Comment by coatesap** [comment]
Looks good. Are these changes backwards-incompatible, or can they also be merged in the v1 branch?

**Comment by CristianLlanos** [comment]
Everything should work exactly the same for the v1 branch. I've changed some method signatures that no one should be using (hopefully). Considering that the v1 branch is very recent I think it might be safe to merge it.

I need to do one more check to compare models generated from v1 vs v2 🙈. Just to be extra sure I didn't accidentally change something in the scaffolding algorithm. I'll confirm my findings later today :)

**Comment by CristianLlanos** [comment]
Hey, @coatesap. I checked model generation results on v1 and v2 and there is no difference on my end. As for the small refactor, it seems to be compatible with v1. I've added a couple of minor changes in v2 (code style mostly).

I would value another opinion on model generation before merging v2 into v1, though.

This is what I did in my manual test:
1. Generate models using v1 for a production database.
2. Make a commit with those models using git
3. Install v2 in the same project
4. Remove the Models folder. `rm -rf app/Models`. If `base_files` are enabled, this step is not advised because step 6 might become polluted with changes.
5. Generate models using v2 for the same production database.
6. Run `git diff` and see if there are any changes.
7. If there are no changes whatsoever, then everything is fine and we can assume v2 is backwards-compatible.

The things one has to do when there is a lack of convenient automated tests covering the main functionality 😂.

**Comment by AdamLenda** [comment]
I believe we agree that...

1. the output of the existing command should not change

We may need to discuss...

2. the new code:dto command should exist in parallel to generate either all
DTOs or one for the specified table, and use the same "base DTO w/
inheritance" to support customization
3. the new code:map command should exist in parallel to generate "best
guess" Model to DTO mappings that can then be overridden in the same way

In an ideal world...

> artisan code:dto --table user --table role_users --table permission_roles

Generates...

- UserDto extends BaseUserDto
- RoleUserDto extends BaseRoleUserDto
- PermissionDto extends BasePermissionDto

Still working on the right way to generate the mappings for Models to DTO.

To my mind, the goal should be to support both this:

> artisan code:map --model Permission --dto PermissionDto --map
PermissionMap

where PermissionMap has functions
- fromPermissionModelToPermissionDto(Permission $permission) : PermissionDto
- fromPermissionModelsToPermissionDtos(array $permissions): array

and:

> artisan code:map --model Permission --model User --dto PermissionUser
--map PermissionUserMap

which creates the new DTO:

PermissionUserDto extends BasePermissionUserDto

And a new Mapping:

PermissionUserMap extends BasePermissionUserMap

with functions:

- fromPermissionModelToPermissionUserDto(Permission $permission):
PermissionUserDto

- fromPermissionModelsToPermissionUserDtos(array $permissions): array

**Comment by CristianLlanos** [comment]
Hi, Adam,

(sorry, guys, if this is too long. It's OK if you'd like to continue the discussion over a voice channel)

## 1. I concur.

## As for points 2 and 3 I have some questions:

### a) Is it a common use case to have DTOs and no Eloquent Models in the same codebase?

Would it be something a Laravel developer would consider? I understand we could use the Laravel Query Builder and forget about Eloquent Models. Is it something common? Is it something we should to consider? I may be biased here. I will value your opinion on this, @AdamLenda.

### b) If we agree that developers who enable generation of Eloquent Models and DTOs would also want to have their Mappers at the same time
How often would they generate DTOs and not their Eloquent Models? I believe that doing these processes in separe times may lead to implementation errors.

Having this in mind I see two possible design decisions to make:
#### I. We add a couple of new boolean keys to the `config/models.php` file
These keys would enable DTO and Mapper generation. The `code:models` command would take those configurations in mind when doing its job.

The config file may look like this:
```php
// config/models.php

return [
    '*' => [ // All current models inherit these configurations
        'make' => [
            'model' => true, // In case there is value in `a)`, we could allow for this :)
            'dto' => true,
            'mapper' => true,
        ],
    ],

    'timezones' => [ // Overrides for this particular table
        'make' => [
            // 'model' => true, // Inherited from *
            // 'dto' => true, // Inherited from *
            'mapper' => false, // Maybe for some reason we don't want a mapper for this table
        ],
    ],

    'countries' => [ // Overrides for this particular table
        'make' => [
            'model' => false, // We don't want models for this table
            'dto' => true, // We only want a DTO
            'mapper' => false, // No mapper needed
        ],
    ],
];
```

#### II. We deprecate the `code:models` command
And expose a more generalist one (not sure about the name yet, maybe `code:entities`) that would generate Eloquent Models, DTOs and Mappers when required through the project's configuration (see previous `config/models.php` example).


## Etymology and philosophy
One of the core values of these package is its API simplicity. The `code:models` command was born under the idea that as a developer we like to have control over how things are being done, but we are lazy enough not to remember how to do those configurations every time. This is why the `config/models.php` file exists, to be a convenient place to configure our scaffolding algorithm and just run a simple command, easy to remember, just in case we changed our database.

For performance reasons the options to generate models by table, schema or connection were added. Though these options are not encouraged. We get a more accurate scaffolding output when doing a complete analysis of the entire database and foreign key connections.

## Config, DTOs and Mappers Draft

This is a draft version of our config file that would also allow us to configure DTOs and Mappers. Configuration key names and structure, as well as method and class names are a proposal and more suitable naming / structure suggestions are encouraged.

```php
// config/models.php

return [
    'entity' => [ // All models will inherit these configurations. Replaces '*' that previously inherited to all models
        'make' => [
            'model' => true, // In case there is value in `a)`, we could allow for this :)
            'dto' => true,
            'mapper' => true,
        ],
    ],

    'dto' => [
        'suffix' => 'Dto', // By default
        'compose' => [
            [
                  'as' => 'UserPermission', // We should get UserPermissionDto and UserPermissionMapper with their base files
                  'tables' => [
                       // We should consider fully qualified table names (with schema)
                      'identity.users',

                      // When there is no collision, table name under default connection schema would be more than enough
                      'permission',
                  ],
                  'make' => [
                      'mapper' => true, // We are telling it to also generate a mapper class
                  ],
            ],
        ],
    ],

    'mapper' => [
        'suffix' => 'Mapper', // By default
    ],
];
```
These are my thoughts on composing DTOs.

```php
// permissions table
// - id (unsigned bigint)
// - rule (varchar)

// Let's say a user can one have one permission for the sake of simplicity

// users table
// - id (unsigned bigint)
// - name (varchar)
// - permission_id (unsigned bigint, reference id on table permission)


// Generated DTO for permissions table
class PermissionDto extends BasePermissionDto {
    public function setId(float $id): PermissionDto {}
    public function getId(): float {}

    public function setRule(string $rule): PermissionDto {}
    public function getRule(): string {}
}

// Generated DTO for users table
class UserDto extends BaseUserDto {
    public function setId(float $id): UserDto {}
    public function getId(): float {}

    public function setName(string $name): UserDto {}
    public function getName(): string {}

    public function setPermissionId(float $permissionId): UserDto {}
    public function getPermissionId(): float {}
}

// Composite DTO generation rules for UserPermission composite DTO
class UserPermissionDto extends BaseUserPermissionDto {
    /**
     * We could use first DTO as main DTO
     * and inherit its methods as they are in their own DTO
     */

    public function setId(float $id): UserPermissionDto {}
    public function getId(): float {}

    public function setName(string $name): UserPermissionDto {}
    public function getName(): string {}

    public function setPermissionId(float $permissionId): UserPermissionDto {}
    public function getPermissionId(): float {}


    /**
     * As for the other entities, we could prepend their model name
     * to avoid method name collisions
     */

    // So these methods from [PermissionDto]
    public function setId(float $id): UserPermissionDto {}
    public function getId(): float {}

    public function setRule(string $rule): UserPermissionDto {}
    public function getRule(): string {}

    // Become these
    public function setPermissionId(float $id): UserPermissionDto {}
    public function getPermissionId(): float {}

    public function setPermissionRule(string $rule): UserPermissionDto {}
    public function getPermissionRule(): string {}

    // The problem is that we now have a collision (setPermissionId, getPermissionId)
    // because permission_id is a property from the users table and it has the same method names.

    // We could make it smart enough as to keep only one of these repeated methods
    // And so it would end up just adding:
    public function setPermissionRule(string $rule): UserPermissionDto {}
    public function getPermissionRule(): string {}
    // This may be deceiving, though. Even though some of these "smart conflict resolutions"
    // may be correct, there may be cases in which different data may go to each of the mapping
    // fields. I don't think it is a common case.

}

// Generated Composite DTO after rules where applied for UserPermission composite DTO
class UserPermissionDto extends BaseUserPermissionDto {
    public function setId(float $id): UserPermissionDto {}
    public function getId(): float {}

    public function setName(string $name): UserPermissionDto {}
    public function getName(): string {}

    public function setPermissionId(float $permissionId): UserPermissionDto {}
    public function getPermissionId(): float {}

    public function setPermissionRule(string $rule): UserPermissionDto {}
    public function getPermissionRule(): string {}

}

// Generated Mapping for UserPermission composite DTO made from User and Permission models
class UserPermissionMapper extends BaseUserPermissionMapper {
    /**
     * From Permission and User to UserPermissionDto
     */
    public function compose(User $user, Permission $permission): UserPermissionDto {}

    public function asUser(UserPermissionDto $userPermissionDto): User {}

    public function asPermission(UserPermissionDto $userPermissionDto): Permission {}

    /**
     * I believe we need some other abstraction to do multiple processing.
     * 
     * Having an index based parameter seem fragile
     * 
     * From [User, Permission][] to UserPermissionDto[]
     */
    public function composeThese(array $models): array {
        $userPermissionDtos = [];

        foreach ($models as $model) {
            // This is a very fragile style. It is so easy to invert the order and get an error
            $userPermissionDtos[] = $this->compose(
                $model[0], // User
                $model[1]  // Permission
            );
        }

        return $userPermissionDtos;
    }

    /**
     * What about using another DTO 🤣
     * 
     * From UserPermissionBag[] to UserPermissionDto[]
     */
    public function composeThese(array $models): array {
        $userPermissionDtos = [];

        foreach ($models as $model) {
            $userPermissionDtos[] = $this->compose(
                $model->getUser(),
                $model->getPermission()
            );
        }

        return $userPermissionDtos;
    }
}

class UserPermissionBag {
    public function __construct(User $user, Permission $permission) {}
    public function getUser(): User {}
    public function getPermission(): Permission {}
}
```

My conclusions on composing DTOs is that it will add a good deal of complexity to the codebase. Seems like a cool idea when implemented correctly. Moreover, Adding an object such as `UserPermissionBag` seems to be important for these composite DTOs. Otherwise, we'll end up handling indexed values (a door to fragile code in my view).

**Pull request merged**
