### PR TITLE
fix relations when table qualify is enabled

### PR DESCRIPTION
**Pull request by gareth-ib**

### CODE REVIEW

**Comment by CristianLlanos** [comment]
Would you mind providing an actual example of the error and how this code fixes it, please?

**Comment by gareth-ib** [comment]
table can not be found, because it didn't include the qualifier ("schema" for postgres, "database" for mysql).
there's a lot of these errors.. I added them into my postgres fix, too tedious doing this over and over

**Comment by CristianLlanos** [comment]
@gareth-ib, do you happen to have a sample Postgres database where I can run this package and see the errors myself?

**Comment by CristianLlanos** [comment]
A way to replicate this issue would be tremendously helpful. And thanks for taking the time to contribute.

**Pull request closed without merging**
