### PR TITLE
Support connection specific config

### PR DESCRIPTION
**Pull request by finiteinfinity**
This PR enables support for connection specific config, useful for if you want to modify config based on the connection defined from the `--connection` option.

### CODE REVIEW

**Comment by CristianLlanos** [comment]
Would you mind providing more examples on how this can be useful?

**Comment by finiteinfinity** [comment]
Hi @CristianLlanos,

I've updated the `models.php` config file with a more real world example. Similarly to what I have added to the config, 
my use case requires me to run a second connection with read-only permissions and as such I'd like models built from that connection to extend a parent model that enforces this through Laravel's event observers.

**Comment by CristianLlanos** [comment]
Do you think it is possible to optimise this `get` method a bit? 🙊

**Comment by finiteinfinity** [comment]
I've refactored the method like you asked and added some basic unit tests too 😄

**Review by CristianLlanos — APPROVED** [review]

**Comment by CristianLlanos** [comment]
Thanks for sharing with the community :)

**Comment by CristianLlanos** [comment]
I've changed the `connections` key to `@connections` in order to prevent collisions on current config files.

**Pull request merged**
